language: ruby
rvm:
- 2.3.3
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
branches:
  only:
  - master
sudo: false
deploy:
  provider: s3
  access_key_id: AWS_ACCESS_KEY
  secret_access_key: AWS_SECRET_KEY
  bucket: www.nolanscafe.co.uk
  skip_cleanup: true
  local_dir: _site
env:
  matrix:
  - secure: Wn5P+ojk/1lGyiPpCcjuGmkM560LZMopjHFm1NC8JTHW0qrfp8U3jQXKyz3ihK+RsJKuFE5QR9O9DOu8/tXop07s0SNjkDCCY1AyGNwDTIqe9RkZp9cD+eKrOEXyO8QQ6szHvYeTeFHXVCi3InaQ1eCDGtmHU3A28qVxWI2u3hKMYlOjRA7vr8TMHlhEzG1nTNMuR/9znsLQFuHD9yDTr3kPxAavef+qLZ0GUd0P4ddwt/5uHW81KAZ4yCyfid6v3C0GpUnc8i2oFg4GxRrV8gNcnEmFfgdmPuNIRQ1ErOEqZZo/gCDmTI47FbIUQJc0mHHNmO5m+sxr13VtVqHbUrRNomDtMHSj+4jeWvOY0CLH2kMeRD3ulwsVaZ9WKwpTDkXZ+95B7O+2NdGcxEvRshIL2HUh23QfUTmOIaa3Z8FY84rdgjxcoTOxeSRlcsAHGnkS4zQ+A7O0Hy0Bl2jCeMh/THC0sHxaoQoJ5/aUYBM12wEDkRvKDr/Rj309UWsZiUuIo9k4Uv5rxPiG652mAYI1wKYomYzi13luYEAFTTl0uHR1QoVdPie91NPAZo6ez1XuCXRteFWLOAn5JO1L2RQAljm0vxx6JGw7Q4z8hA70wPx2PMwv6PIZMQbD2pSOIskZ2dFc96tHeMuOO76VtOJG8ywcMKFntLiniavkNZc=
  - secure: lxfyx9yga1pyqyzOTR3Xy1z2i1lxXBUuMxIbGdklXTuG9YrKtk2Z6Z+WvGU7Uk5q/L+0kZU6kaB6nWD4mtNZrLKkqomLi8HyxO8otpt4u6Ulnd8MAy2PS1+xwz+NKqBaQuD6GbzHCrKZT8VUaAjuCEim/+rUPQyQA8V2BSg6QWITTlyVzQeAYFdgWFOVX9+llKl0XAMHchUM1dCqOy3CluMJiQ+irmOPiFSCJIgyvcTEkSkDy++CDhme9ucsj+qcKcSTsnPyCCmUz960K2Qfl8Rro+m8KBtWmiGPKkJe6JZRiUX2IG2u8zJTMWs22XGI9/ZF0xgv/X1ttj1NvOgIlKmdsU3Mu3ovxJowyYEloKUCHq9i+VA4DQfhsVeq0FCMStRqvTaqe1i8tTI7ekoCnaKoM/Uts+uu0nJNYxuo5oqh4YW5sWQHXew53ad/b1yWoBlZ/AKauKZ9WD6eZJhBf6H/mRlH/9dbSn0ji2itBogaeRkIVRYlGx9mE6ibG6YeuhhJYPTvScI7jXKxv+kTmZjGp5ba7HYYy6QBVJAMIVR+uPD56tD5jr9HOsNSyUaI91Q3d9OGaprThArV5Uj1GUQIqwbp15JwDVEF7TPzpTlkuXkaBqNLURZpDCz/8BeV+Z7yqVBOOZavUWx3ZLGCLgTaU+EBuIoKlCTY6BQEb+4=
