language: ruby
install: pip install awscli
rvm:
- 2.3.3
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
branches:
  only:
  - master
sudo: false
deploy:
  provider: s3
  access_key_id:
    secure: h+RL1760xtk6FxkpLhB5aLaI9Tim5uBD0jah63BhcqE/b/G9hNSbUOfvioBt0BQfAofz2vifUgbV42iiK+/Jh1XaK4lze0UPZForL4/ex9T8Ov78rqk/8hrwnmn9tLfAWuR6366B7jFTUPpbLHagdMyYTwhoJKHeeaDY2aOlizAWlbTBjWeqL+DvjbXjlYT0nNIWIS03KbdgtUNtBCOtIS48nprzKyJJC0JCtKhyn1KekaEh61V8Q1sI9A+l990YsbrIvQz46Zsa+noBbWsr8do/N4fkh4tzt81/qTNgMK6sMNUffM7jhEVKQU2Bm9UxHGGjV4XGu4XJXH5idYb+Ut/6Ebv4jTb5rNn2GkX0mdjOFloPxYXZMIP4iQ3K5+4sM6NQq/RWWJAnLjaXGPnsGi7XuzleHDJWSQ2ZIS03hmqhsBWx5g9UCsLWaKOgVtZkIfTSBoJ/eZlzbA+tK5ZiJp5iTWE/7KF/UhDhoIIXBxBWRJRakv6d5Ni4T0x69Y1VWOkzN68RqH9B2XkMBMNxfwKt6MUGE5I3GkTLRCChS/1v4RpNqfKUMT9xEIwM44fD+MXjxhGZ71WIOoDaPT7EInnQLH92FAaXW3gk5sYd/pQSLqid3IF9tsAbg94jgVpqQVHjsnT6e/NJMT96je/xUKnPleoW/CUmyyihrue6CWU=
  secret_access_key:
    secure: iWJL9PsENahzCma/CrWcCizRBKu5NcIj+tu7mQHpk1TllyUPl0dEWrGX5XBcXg/evxfz0Zy+V8AEN9msIWjMkd4ZmCvn9f2v06W5G8rSpylQegZmQ9KLzN5P4vaNrbbOSLtcxSvxi2SNdnhW+f9WCA2cBWxQ+31OSZ3UxWodyr+aotDk/ACFxpAuji2OurGsW+5kFW2XMNAd/sFaekTv9+qawuPtJjkLLXCDp3uuyg4O/QE0FS3SR/wIlSVjqBBJDVfsUNx0fY5H0saKRmWtx9XUT28U+vPwZhCAphKLSg8j40LWs97eKhL7bXrZ8JeZlRLMoWgqYIkBC0KglOJYkKx65Fy9sAM2woC2eU2cErrFrxdIXyD8FYrV9N0dIpD9ATOUkmJtDr1G0zbnfJ/sAp/79nJsBNep0dh9+7WrdcKMWAN/2voHkJSi5hSJpSPrstDSXIn+oBC1DFuxiZmzrJTZwwjJXrd+2JhhpqqmRLBsBW7Pw2kz6DYd8Qadr8P6SRfRQRVGDiWcc5xvlGNcYFjwvdu+Rf5ymXYhORttGPldDtOA9phIEThN2tYlzjoNdnkpZn4R01haUrRl3OGHDz8KC3jOznJfmQQK6jGNNQNCD+laK0cKuxEsXalqQkqIgELPKkLTlbpYeSDeMq9GGWi199yhlfLYg+J1ut3X4f8=
  bucket: www.nolanscafe.co.uk
  skip_cleanup: true
  local_dir: _site
  region: eu-west-1