# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adventures in Front End Development and Leadership/Coaching
email: johnnolan@nolanscafe.co.uk
description: > # this means to ignore newlines until "baseurl:"
  I aim to record my successes and mistakes here so that others
  may learn from them.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://johnnolan.github.io" # the base hostname & protocol for your site
github_username:  johnnolan

# Build settings
markdown: kramdown
sass:
  style: compressed