# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
version: 1559752446335
title:  Front End Development, React, Redux and others
email: me@johnnolan.dev
description: > # this means to ignore newlines until "baseurl:"
  Brain dump blog for all Front End Development, React, Redux and any other problems I face and solve
baseurl: "" # the subpath of your site, e.g. /blog
canonical_baseurl: "/amp" # the subpath of your site, e.g. /blog
url: "https://www.johnnolan.dev" # the base hostname & protocol for your site
github_username:  johnnolan

exclude:   [nodemodules, script, Gemfile, npm-debug.log, browserconfig.xml, package.json]

# Build settings
markdown: kramdown
sass:
  style: compressed
