# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
version: 1539107168222
title:  John Nolan
email: johnnolan@nolanscafe.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Coding, Leadership and Coaching
baseurl: "" # the subpath of your site, e.g. /blog
canonical_baseurl: "/amp" # the subpath of your site, e.g. /blog
url: "https://www.nolanscafe.co.uk" # the base hostname & protocol for your site
github_username:  johnnolan

exclude:   [nodemodules, script, Gemfile, npm-debug.log, browserconfig.xml, package.json]

# Build settings
markdown: kramdown
sass:
  style: compressed
