# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Random thoughts on leadership
email: johnnolan@nolanscafe.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Trials and tribulations of running your own development team, 
  dealing with conflict, personalities and politics in the workplace.
  Plus how I find treating people gets the best from them.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://johnnolan.github.io" # the base hostname & protocol for your site
github_username:  johnnolan

# Build settings
markdown: kramdown
