# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
version: 24
title:  Front End Development and Leadership/Coaching
email: johnnolan@nolanscafe.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Front end guides and Coaching / Leadership experiences
baseurl: "/amp" # the subpath of your site, e.g. /blog
canonical_baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.nolanscafe.co.uk" # the base hostname & protocol for your site
github_username:  johnnolan

# Build settings
markdown: kramdown
sass:
  style: compressed

destination:   _site/amp
layouts_dir:   ./_layouts-amp
exclude:   [nodemodules, script, Gemfile, npm-debug.log, sw.js, browserconfig.xml, package.json, favicon.ico]

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "default"
